# These are supported funding model platforms

github: [521xueweihan]
custom: ['https://hellogithub.com/', 'https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA5MzYyNzQ0MQ==&action=getalbum&album_id=1331197538447310849&scene=173&from_msgid=2247509396&from_itemidx=1&count=3&nolastread=1#wechat_redirect']
